default_stages: [push]
repos:
  - repo: local
    hooks:
      - id: run-all-tests
        name: run all tests
        entry: ./scripts/run-tests.sh
        language: script
        pass_filenames: true
        verbose: true
