version:  '3.8'
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=user
      - MYSQL_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=revamp_registry
      - MYSQL_HOST=localhost
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
